[package]
name = "annex"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs", "io-util", "process", "signal"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
directories = "5"
notify = { version = "6", default-features = false, features = ["macos_kqueue", "serde"] }
parking_lot = "0.12"
futures = "0.3"
regex = "1"