[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
serde_json = "1"
jsonschema = "0.17"

[dev-dependencies]
